[package]
name = "builder"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.45.1", features = ["process", "io-util", "rt", "time", "macros"] }
anyhow = "1.0"
colored = "3.0" 
